# Generated by Django 5.2.8 on 2025-12-11 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_update_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cita',
            name='unique_cita_slot',
        ),
        migrations.RenameIndex(
            model_name='cita',
            new_name='citas_cita_estado_4ca04c_idx',
            old_name='citas_cita_estado_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='cita',
            new_name='citas_cita_cliente_e2cc4a_idx',
            old_name='citas_cita_cliente_fecha_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('fecha', 'hora', 'servicio')},
        ),
    ]
